version: '3'

services:
  app:
    build:
      context: .
      dockerfile: bot/Dockerfile
      environment:
        - telegram-token=${telegram-token}
        - telegram-chat=${telegram-chat}
    volumes:
      - '.:/opt/app'