version: '3'

services:
  app:
    image:
      thegreentea/electricity_outage_bot
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_CHAT: ${TELEGRAM_CHAT}
    volumes:
      - '.:/opt/app'
