version: '3'

services:
  app:
    build:
      context: .
      dockerfile: bot/Dockerfile
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_CHAT: ${TELEGRAM_CHAT}
    volumes:
      - '.:/opt/app'
