version: '3'

services:
  app:
    build:
      context: .
      dockerfile: bot/Dockerfile
  args:
    - telegram-token=${telegram-token}
    - telegram-chat=${telegram-chat}
    volumes:
      - '.:/opt/app'