name: Build

on:
 push:
   branches:
     - '*'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.9'
        - name: Install dependencies
          run: |
            python -m venv .venv
            source .venv/bin/activate
            python -m pip install --upgrade pip
            python -m pip install poetry
            poetry install
        - name: Run linters and formaters
          run: |
            .venv/bin/flake8 --jobs 4 --statistics --show-source tests bot
            .venv/bin/pylint --jobs 4 --rcfile=setup.cfg tests bot
            .venv/bin/mypy tests bot
            .venv/bin/black --skip-string-normalization --check tests bot
        - name: Run tests
          run: .venv/bin/pytest -v tests --cov-report=xml
        - name: Upload coverage report
          uses: codecov/codecov-action@v1
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            files: ./coverage.xml
            flags: unittests
            env_vars: OS,PYTHON
            name: codecov-umbrella
            fail_ci_if_error: true
            verbose: true